language: go
sudo: false

jobs:
  include:
    - stage: build
      script: go build -x
    - stage: test
      before_script: chmod u+x ./copy_lib.sh && ./copy_lib.sh
      script: go test ./api -v